//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.tiger.quicknews.adapter;

import android.content.Context;

public final class ImageAdapter_
    extends ImageAdapter
{

    private Context context_;

    private ImageAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static ImageAdapter_ getInstance_(Context context) {
        return new ImageAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
