//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.tiger.quicknews.adapter;

import android.content.Context;

public final class NewAdapter_
    extends NewAdapter
{

    private Context context_;

    private NewAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static NewAdapter_ getInstance_(Context context) {
        return new NewAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
